title: OSU-Wisconsin Consumer Credit Panel
page-top-title: OSU-WI CCP
top-section-bg-text: OSU-Wisconsin Consumer Credit Panel
home-subtitle: About
copyright-text: '&copy; The Ohio State University 2026. All Rights Reserved.'
